/** Shortlist for dropdowns — users can type further detail in notes if needed */
export const COUNTRY_OPTIONS = [
  "Australia",
  "New Zealand",
  "United Kingdom",
  "United States",
  "Canada",
  "India",
  "Pakistan",
  "Bangladesh",
  "Sri Lanka",
  "Nepal",
  "Philippines",
  "China",
  "Hong Kong SAR",
  "Singapore",
  "Malaysia",
  "Indonesia",
  "Thailand",
  "Vietnam",
  "Japan",
  "South Korea",
  "United Arab Emirates",
  "Saudi Arabia",
  "Egypt",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Ireland",
  "Brazil",
  "Mexico",
  "Other",
] as const;
